### ISSUE TITLE
Batched environment is not closed 

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/rl#97]
Error Log:

```
Traceback (most recent call last):
  File "/private/home/sodhani/projects/rl/torchrl/envs/vec_env.py", line 256, in __del__
RuntimeError: Batched environment must be explicitely closed before it turns out of scope.
```
Full Trace:

```
(torch_rl) ➜  rl git:(main) ✗ python examples/ppo/ppo.py --config=examples/ppo/configs/humanoid.txt --total_frames=10

/private/home/sodhani/.conda/envs/torch_rl/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:228: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  interpolation: int = Image.BILINEAR,
...
  interpolation: int = Image.NEAREST,
/private/home/sodhani/.conda/envs/torch_rl/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:328: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  interpolation: int = Image.BICUBIC,
collector = MultiSyncDataCollector();
loss_module = ClipPPOLoss(
  (actor): ProbabilisticActor(module=NormalParamWrapper(
    (operator): MLP(
      (0): Linear(in_features=67, out_features=400, bias=True)
      (1): Tanh()
      (2): Linear(in_features=400, out_features=300, bias=True)
      (3): Tanh()
      (4): Linear(in_features=300, out_features=42, bias=True)
    )
  ), distribution_class=<class 'torchrl.modules.distributions.continuous.TanhNormal'>, device=cuda:0)
  (critic): ValueOperator(
      module=MLP(
        (0): Linear(in_features=67, out_features=400, bias=True)
        (1): Tanh()
        (2): Linear(in_features=400, out_features=300, bias=True)
        (3): Tanh()
        (4): Linear(in_features=300, out_features=1, bias=True)
      ),
      device=cuda:0,
      in_keys=['observation_vector'],
      out_keys=['state_value'])
);
recorder = TransformedEnv(env=DMControlEnv(env=humanoid, task=walk, batch_size=torch.Size([])), transform=Compose(
	VideoRecorder(keys=['next_pixels']),
	RewardScaling(loc=0.0000, scale=1.0000, keys=['reward']),
	CatTensors(in_keys=['next_com_velocity', 'next_extremities', 'next_head_height', 'next_joint_angles', 'next_torso_vertical', 'next_velocity'], out_key=next_observation_vector),
	ObservationNorm(keys=['next_observation_vector']),
	DoubleToFloat(keys=['reward', 'action', 'next_observation_vector']),
	FiniteTensorDictCheck(keys=[])));
target_net_updater = None;
policy_exploration = ProbabilisticActor(module=NormalParamWrapper(
  (operator): MLP(
    (0): Linear(in_features=67, out_features=400, bias=True)
    (1): Tanh()
    (2): Linear(in_features=400, out_features=300, bias=True)
    (3): Tanh()
    (4): Linear(in_features=300, out_features=42, bias=True)
  )
), distribution_class=<class 'torchrl.modules.distributions.continuous.TanhNormal'>, device=cuda:0);
replay_buffer = None;
writer = <torch.utils.tensorboard.writer.SummaryWriter object at 0x7f8c20dc7430>;
args = Namespace(config='examples/ppo/configs/humanoid.txt', optim_steps_per_collection=10, optimizer='adam', selected_keys=None, batch_size=256, log_interval=10000, lr=0.0003, weight_decay=2e-05, clip_norm=1.0, clip_grad_norm=False, normalize_rewards_online=True, sub_traj_len=-1, collector_devices='cpu', pin_memory=False, init_with_lag=True, frames_per_batch=250, total_frames=2, num_workers=32, env_per_collector=8, seed=42, exploration_mode=None, async_collection=False, env_library='dm_control', env_name='humanoid', env_task='walk', from_pixels=False, frame_skip=4, reward_scaling=1.0, init_env_steps=250, vecnorm=False, norm_rewards=False, noops=0, max_frames_per_traj=250, loss='clip', gamma=0.99, lamda=0.95, entropy_factor=0.0001, loss_function='smooth_l1', tanh_loc=True, gSDE=False, default_policy_scale=1.0, distribution='tanh_normal', lstm=False, shared_mapping=False, record_video=True, exp_name='', record_interval=200, record_frames=250);

  0%|                                                                                                                                                                                           | 0/8 [00:00<?, ?it/s]1 is done!
2 is done!
0 is done!
3 is done!
grad_norm: 4.5215, optim_steps: 10.0000, loss_objective: 0.5818, entropy: 13.2145, loss_entropy: -0.0013, loss_critic: 0.3802, ESS: 0.6759, reward_training: 0.1401: : 1024it [00:00, 1958.13it/s]Exception ignored in: <function _BatchedEnv.__del__ at 0x7f8c22dcea60>
Traceback (most recent call last):
  File "/private/home/sodhani/projects/rl/torchrl/envs/vec_env.py", line 256, in __del__
RuntimeError: Batched environment must be explicitely closed before it turns out of scope.
grad_norm: 4.5215, optim_steps: 10.0000, loss_objective: 0.5818, entropy: 13.2145, loss_entropy: -0.0013, loss_critic: 0.3802, ESS: 0.6759, reward_training: 0.1401: : 1024it [00:01, 575.76it/s]
```

**Comment by shagunsodhani** [comment]
>One solution would be to automatically close the env in __del__, do you see any downside to that?

Sounds reasonable.

>But we need to close it in PPO script,

I actually could not figure out how to do that. Is the env an attribute of the collector?

**Comment by vmoens** [comment]
Closed as per #98
